# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AssignmentApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AssignmentApp
	pod 'ReachabilitySwift'
	pod 'SVProgressHUD'
	pod 'IQKeyboardManagerSwift'
  target 'AssignmentAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssignmentAppUITests' do
    # Pods for testing
  end

end
